<?php
$route['v1/api/create/vehicle']='api/v1/api/create_vehicle';
$route['v1/api/list/vehicle']='api/v1/api/list_vehicle';
$route['v1/api/list/shipper']='api/v1/api/list_shipper';
$route['v1/api/list/trip']='api/v1/api/list_trip';
$route['v1/api/auth/user']='api/v1/api/auth_user';
$route['v1/api/create/consignment']='api/v1/api/create_consignment';
$route['v1/api/create/trip']='api/v1/api/create_trip';
$route['v1/api/update/location/trip']='api/v1/api/update_trip_location';
